#pragma once
#include <stdint.h>


// The ADC9 uses 2000mV voltage ref chip MCP1501
#define ADC9_VREF_MICRO_VOLT 2048*1000
#define TIABT_VREF_MICRO_VOLT 3000*1000

typedef enum {
	APP_START,
	APP_WAITING,
	APP_INIT_ADC,
	APP_PRINT_ADC
} app_state_t;

typedef enum {
	MY_LEDS_OTHER,
	MY_LEDS_BEATS,
	MY_LEDS_WAITING,
	MY_LEDS_COUNT
} my_leds_t;

typedef enum {
	MYGATT_SRV1,

	MYGATT_SRV2,
	MYGATT_SRV2_CH0_CHRC0,
	MYGATT_SRV2_CH0_CHRC1,
	MYGATT_SRV2_CH0_CCC,
	MYGATT_SRV2_CH0_CUD,
	MYGATT_SRV2_CH0_CPF,
	MYGATT_SRV2_CH1_CHRC0,
	MYGATT_SRV2_CH1_CHRC1,
	MYGATT_SRV2_CH1_CCC,
	MYGATT_SRV2_CH1_CUD,
	MYGATT_SRV2_CH1_CPF,
	MYGATT_SRV2_CH2_CHRC0,
	MYGATT_SRV2_CH2_CHRC1,
	MYGATT_SRV2_CH2_CCC,
	MYGATT_SRV2_CH2_CUD,
	MYGATT_SRV2_CH2_CPF,
	MYGATT_SRV2_CH3_CHRC0,
	MYGATT_SRV2_CH3_CHRC1,
	MYGATT_SRV2_CH3_CCC,
	MYGATT_SRV2_CH3_CUD,
	MYGATT_SRV2_CH3_CPF,
	MYGATT_SRV2_CH4_CHRC0,
	MYGATT_SRV2_CH4_CHRC1,
	MYGATT_SRV2_CH4_CCC,
	MYGATT_SRV2_CH4_CUD,
	MYGATT_SRV2_CH4_CPF,
	MYGATT_SRV2_CH5_CHRC0,
	MYGATT_SRV2_CH5_CHRC1,
	MYGATT_SRV2_CH5_CCC,
	MYGATT_SRV2_CH5_CUD,
	MYGATT_SRV2_CH5_CPF,
	MYGATT_SRV2_CH6_CHRC0,
	MYGATT_SRV2_CH6_CHRC1,
	MYGATT_SRV2_CH6_CCC,
	MYGATT_SRV2_CH6_CUD,
	MYGATT_SRV2_CH6_CPF,
	MYGATT_SRV2_CH7_CHRC0,
	MYGATT_SRV2_CH7_CHRC1,
	MYGATT_SRV2_CH7_CCC,
	MYGATT_SRV2_CH7_CUD,
	MYGATT_SRV2_CH7_CPF,

	MYGATT_SRV3,
	MYGATT_SRV3_DPOT0_CHRC0,
	MYGATT_SRV3_DPOT0_CHRC1,
	MYGATT_SRV3_DPOT0_CCC,
	MYGATT_SRV3_DPOT0_CUD,
	MYGATT_SRV3_DPOT0_CPF,

	MYGATT_SRV3_DPOT1_CHRC0,
	MYGATT_SRV3_DPOT1_CHRC1,
	MYGATT_SRV3_DPOT1_CCC,
	MYGATT_SRV3_DPOT1_CUD,
	MYGATT_SRV3_DPOT1_CPF,

	MYGATT_SRV3_DPOT2_CHRC0,
	MYGATT_SRV3_DPOT2_CHRC1,
	MYGATT_SRV3_DPOT2_CCC,
	MYGATT_SRV3_DPOT2_CUD,
	MYGATT_SRV3_DPOT2_CPF,

	MYGATT_SRV3_DPOT3_CHRC0,
	MYGATT_SRV3_DPOT3_CHRC1,
	MYGATT_SRV3_DPOT3_CCC,
	MYGATT_SRV3_DPOT3_CUD,
	MYGATT_SRV3_DPOT3_CPF,

	MYGATT_SRV3_DPOT4_CHRC0,
	MYGATT_SRV3_DPOT4_CHRC1,
	MYGATT_SRV3_DPOT4_CCC,
	MYGATT_SRV3_DPOT4_CUD,
	MYGATT_SRV3_DPOT4_CPF,

	MYGATT_SRV3_DPOT5_CHRC0,
	MYGATT_SRV3_DPOT5_CHRC1,
	MYGATT_SRV3_DPOT5_CCC,
	MYGATT_SRV3_DPOT5_CUD,
	MYGATT_SRV3_DPOT5_CPF,

	MYGATT_SRV3_DPOT6_CHRC0,
	MYGATT_SRV3_DPOT6_CHRC1,
	MYGATT_SRV3_DPOT6_CCC,
	MYGATT_SRV3_DPOT6_CUD,
	MYGATT_SRV3_DPOT6_CPF,
	MYGATT_COUNT
} mygatt_t;



typedef enum {
	MYID_ADC_VREF,
	MYID_ADC_TEMP,
	MYID_ADC_CH0,
	MYID_ADC_CH1,
	MYID_ADC_CH2,
	MYID_ADC_CH3,
	MYID_ADC_CH4,
	MYID_ADC_CH5,
	MYID_ADC_CH6,
	MYID_ADC_CH7,

	MYID_DPOT0_WIPER,
	MYID_DPOT1_WIPER,
	MYID_DPOT2_WIPER,
	MYID_DPOT3_WIPER,
	MYID_DPOT4_WIPER,
	MYID_DPOT5_WIPER,
	MYID_DPOT6_WIPER,

	MYID_COUNT
} myid_t;







#define MYFLAG_NOTIFY UINT32_C(0x00000001)
#define MYFLAG_SETVAL UINT32_C(0x00000002)


typedef struct {
	int32_t values[MYID_COUNT];
	int32_t values_flags[MYID_COUNT];
} app_t;

extern app_t app;



char const * myid_t_tostr(myid_t id);
