#pragma once
#include <stdint.h>

#define MYGATTW32_SRV2 0x2A5A20B9
#define MYGATTW32_SRV3 0x2A5A20BA

typedef enum {
	MYGATT_SRV2,
	MYGATT_SRV2_CH0_CHRC0,
	MYGATT_SRV2_CH0_CHRC1,
	MYGATT_SRV2_CH0_CCC,
	MYGATT_SRV2_CH0_CUD,
	MYGATT_SRV2_CH0_CPF,
	MYGATT_SRV2_CH1_CHRC0,
	MYGATT_SRV2_CH1_CHRC1,
	MYGATT_SRV2_CH1_CCC,
	MYGATT_SRV2_CH1_CUD,
	MYGATT_SRV2_CH1_CPF,
	MYGATT_SRV2_CH2_CHRC0,
	MYGATT_SRV2_CH2_CHRC1,
	MYGATT_SRV2_CH2_CCC,
	MYGATT_SRV2_CH2_CUD,
	MYGATT_SRV2_CH2_CPF,
	MYGATT_SRV2_CH3_CHRC0,
	MYGATT_SRV2_CH3_CHRC1,
	MYGATT_SRV2_CH3_CCC,
	MYGATT_SRV2_CH3_CUD,
	MYGATT_SRV2_CH3_CPF,
	MYGATT_SRV2_CH4_CHRC0,
	MYGATT_SRV2_CH4_CHRC1,
	MYGATT_SRV2_CH4_CCC,
	MYGATT_SRV2_CH4_CUD,
	MYGATT_SRV2_CH4_CPF,
	MYGATT_SRV2_CH5_CHRC0,
	MYGATT_SRV2_CH5_CHRC1,
	MYGATT_SRV2_CH5_CCC,
	MYGATT_SRV2_CH5_CUD,
	MYGATT_SRV2_CH5_CPF,
	MYGATT_SRV2_CH6_CHRC0,
	MYGATT_SRV2_CH6_CHRC1,
	MYGATT_SRV2_CH6_CCC,
	MYGATT_SRV2_CH6_CUD,
	MYGATT_SRV2_CH6_CPF,
	MYGATT_SRV2_CH7_CHRC0,
	MYGATT_SRV2_CH7_CHRC1,
	MYGATT_SRV2_CH7_CCC,
	MYGATT_SRV2_CH7_CUD,
	MYGATT_SRV2_CH7_CPF,

	MYGATT_SRV3,
	MYGATT_SRV3_DPOT0_CHRC0,
	MYGATT_SRV3_DPOT0_CHRC1,
	MYGATT_SRV3_DPOT0_CCC,
	MYGATT_SRV3_DPOT0_CUD,
	MYGATT_SRV3_DPOT0_CPF,

	MYGATT_COUNT
} mygatt_t;



typedef enum {
	MYID_ADC_VREF,
	MYID_ADC_TEMP,
	MYID_ADC_CH0,
	MYID_ADC_CH1,
	MYID_ADC_CH2,
	MYID_ADC_CH3,
	MYID_ADC_CH4,
	MYID_ADC_CH5,
	MYID_ADC_CH6,
	MYID_ADC_CH7,

	MYID_DPOT0_WIPER,
	MYID_DPOT1_WIPER,
	MYID_DPOT2_WIPER,
	MYID_DPOT3_WIPER,
	MYID_DPOT4_WIPER,
	MYID_DPOT5_WIPER,
	MYID_DPOT6_WIPER,

	MYID_COUNT
} myid_t;

typedef struct {
	int32_t voltage[MYID_COUNT];
} gatt_values_t;

extern gatt_values_t values;