#include "myuuids.h"

#define MY_UUID_CHRC(x) BT_UUID_INIT_128(BT_UUID_128_ENCODE(0x2A5A20B9, UINT16_C(x), 0x4B9C, 0x9C69, 0x4975713E0FF2))
#define MY_UUID_SRV(x) BT_UUID_INIT_128(BT_UUID_128_ENCODE(0x2A5A20F9, UINT16_C(x), 0x4B9C, 0x9C69, 0x4975713E0FF2))

const struct bt_uuid_128 uuids_srv[MYSRV_UUID_COUNT] = {
MY_UUID_SRV(MYSRV_UUID_SRV0),
MY_UUID_SRV(MYSRV_UUID_SRV1),
MY_UUID_SRV(MYSRV_UUID_SRV2),
MY_UUID_SRV(MYSRV_UUID_SRV3),
};

const struct bt_uuid_128 uuids_chrc[] = {
[MYID_APP_PRINT_MODE] = MY_UUID_CHRC(MYID_APP_PRINT_MODE),
[MYID_ADC_CH0] = MY_UUID_CHRC(MYID_ADC_CH0),
[MYID_ADC_CH1] = MY_UUID_CHRC(MYID_ADC_CH1),
[MYID_ADC_CH2] = MY_UUID_CHRC(MYID_ADC_CH2),
[MYID_ADC_CH3] = MY_UUID_CHRC(MYID_ADC_CH3),
[MYID_ADC_CH4] = MY_UUID_CHRC(MYID_ADC_CH4),
[MYID_ADC_CH5] = MY_UUID_CHRC(MYID_ADC_CH5),
[MYID_ADC_CH6] = MY_UUID_CHRC(MYID_ADC_CH6),
[MYID_ADC_CH7] = MY_UUID_CHRC(MYID_ADC_CH7),
[MYID_ADC_OFFSET] = MY_UUID_CHRC(MYID_ADC_OFFSET),
[MYID_ADC_VCM] = MY_UUID_CHRC(MYID_ADC_VCM),
[MYID_ADC_AVDD] = MY_UUID_CHRC(MYID_ADC_AVDD),
[MYID_ADC_TEMP] = MY_UUID_CHRC(MYID_ADC_TEMP),
[MYID_DPOT0_WIPER] = MY_UUID_CHRC(MYID_DPOT0_WIPER),
[MYID_DPOT1_WIPER] = MY_UUID_CHRC(MYID_DPOT1_WIPER),
[MYID_DPOT2_WIPER] = MY_UUID_CHRC(MYID_DPOT2_WIPER),
[MYID_DPOT3_WIPER] = MY_UUID_CHRC(MYID_DPOT3_WIPER),
[MYID_DPOT4_WIPER] = MY_UUID_CHRC(MYID_DPOT4_WIPER),
[MYID_DPOT5_WIPER] = MY_UUID_CHRC(MYID_DPOT5_WIPER),
[MYID_DPOT6_WIPER] = MY_UUID_CHRC(MYID_DPOT6_WIPER),
};




